import { CommentItem, VideoItem, UserSettings, AnalyticsStats, ReplyHistoryItem } from './types';

export const INITIAL_MOCK_VIDEOS: VideoItem[] = [
  {
    id: 'vid-1',
    youtube_account_id: 'yt-acc-1',
    youtube_video_id: 'dQw4w9WgXcQ',
    title: 'Building a Full-Stack AI SaaS with Next.js 15 & Supabase (2026 Guide)',
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    published_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    comment_count: 42,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vid-2',
    youtube_account_id: 'yt-acc-1',
    youtube_video_id: 'L_LUpnjgPso',
    title: 'How I Built an Automated YouTube Studio with AI Code Assistants',
    thumbnail_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    published_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    comment_count: 89,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vid-3',
    youtube_account_id: 'yt-acc-1',
    youtube_video_id: 'kXYiU_JCYtU',
    title: 'Top 10 Next.js 15 Features You MUST Use Right Now!',
    thumbnail_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    published_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    comment_count: 124,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_MOCK_COMMENTS: CommentItem[] = [
  {
    id: 'comm-1',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-1',
    youtube_comment_id: 'yt-comm-101',
    author_name: 'Alex Developer',
    author_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@alexdev',
    comment_text: 'This video was insanely helpful! How do you handle token refresh logic when the user is offline?',
    published_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 mins ago
    reply_status: 'pending',
    detected_tone: 'question',
    is_spam: false,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[0],
    generated_reply: {
      id: 'gen-1',
      comment_id: 'comm-1',
      reply_text: 'Thank you! For offline token refresh, we store the OAuth refresh_token securely in Supabase RLS tables and run a background endpoint that exchanges it for a new access_token whenever needed.',
      prompt_used: 'Standard American English - Helpful Tone',
      model_used: 'gpt-4o-mini',
      tone: 'question',
      temperature: 0.7,
      is_approved: false,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'comm-2',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-1',
    youtube_comment_id: 'yt-comm-102',
    author_name: 'Sarah CodeCraft',
    author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@sarahcodecraft',
    comment_text: 'Absolute masterclass content 🔥 Subscribed immediately! Keep making these SaaS breakdown tutorials.',
    published_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 mins ago
    reply_status: 'pending',
    detected_tone: 'positive',
    is_spam: false,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[0],
    generated_reply: {
      id: 'gen-2',
      comment_id: 'comm-2',
      reply_text: 'Thank you so much Sarah! Really appreciate the subscription and support—more in-depth SaaS tutorials are already in the works!',
      prompt_used: 'Standard American English - Warm Tone',
      model_used: 'gpt-4o-mini',
      tone: 'positive',
      temperature: 0.7,
      is_approved: false,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'comm-3',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-2',
    youtube_comment_id: 'yt-comm-103',
    author_name: 'Tech Enthusiast',
    author_avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@techenthusiast',
    comment_text: 'The audio volume in the middle segment drops slightly around 4:12. Otherwise, superb video layout!',
    published_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
    reply_status: 'pending',
    detected_tone: 'criticism',
    is_spam: false,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[1],
    generated_reply: {
      id: 'gen-3',
      comment_id: 'comm-3',
      reply_text: 'Thanks for bringing that audio dip at 4:12 to my attention! I will fine-tune the compressor settings for the next upload.',
      prompt_used: 'Standard American English - Respectful Tone',
      model_used: 'gpt-4o-mini',
      tone: 'criticism',
      temperature: 0.7,
      is_approved: false,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'comm-4',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-2',
    youtube_comment_id: 'yt-comm-104',
    author_name: 'MemeLord99',
    author_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@memelord99',
    comment_text: 'Bro automated his YouTube reply workflow just so he could drink coffee while AI does the social interaction ☕😂',
    published_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(), // 5 hours ago
    reply_status: 'pending',
    detected_tone: 'funny',
    is_spam: false,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[1],
    generated_reply: {
      id: 'gen-4',
      comment_id: 'comm-4',
      reply_text: 'Guilty as charged! Work smarter and drink more espresso—that is the developer way.',
      prompt_used: 'Standard American English - Playful Tone',
      model_used: 'gpt-4o-mini',
      tone: 'funny',
      temperature: 0.7,
      is_approved: false,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'comm-5',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-3',
    youtube_comment_id: 'yt-comm-105',
    author_name: 'CryptoBot_X99',
    author_avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@cryptobot',
    comment_text: 'WhatsApp me for free crypto signals +1 800 555 0199 earn $5000 daily guaranteed',
    published_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    reply_status: 'rejected',
    detected_tone: 'neutral',
    is_spam: true,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[2],
    generated_reply: null,
  },
  {
    id: 'comm-6',
    youtube_account_id: 'yt-acc-1',
    video_id: 'vid-3',
    youtube_comment_id: 'yt-comm-106',
    author_name: 'David Miller',
    author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    author_channel_url: 'https://youtube.com/@davidm',
    comment_text: 'Are there any performance differences between Server Actions and API Routes in Next.js 15?',
    published_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    reply_status: 'posted',
    detected_tone: 'question',
    is_spam: false,
    is_duplicate: false,
    is_deleted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    video: INITIAL_MOCK_VIDEOS[2],
    generated_reply: {
      id: 'gen-6',
      comment_id: 'comm-6',
      reply_text: 'Server Actions eliminate boilerplate endpoints for form actions, while API Routes remain ideal for public endpoints or webhooks. Performance is virtually identical under the hood.',
      prompt_used: 'Standard American English - Helpful Tone',
      model_used: 'gpt-4o-mini',
      tone: 'question',
      temperature: 0.7,
      is_approved: true,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

export const INITIAL_DEFAULT_SETTINGS: UserSettings = {
  id: 'sett-1',
  user_id: 'usr-demo',
  openai_api_key: '',
  openai_base_url: 'https://api.openai.com/v1',
  openai_model: 'gpt-4o-mini',
  custom_prompt: 'You are a warm, helpful, engaging YouTube content creator replying to comments on your video. Sound natural, friendly, non-robotic, and strictly 1 to 3 sentences.',
  temperature: 0.7,
  max_tokens: 150,
  reply_length: '1-3 sentences',
  default_tone: 'auto',
  auto_fetch_interval_minutes: 5,
  spam_filter_enabled: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_HISTORY: ReplyHistoryItem[] = [
  {
    id: 'hist-1',
    comment_id: 'comm-6',
    action: 'posted',
    action_by: 'User Approval',
    reply_text: 'Server Actions eliminate boilerplate endpoints for form actions, while API Routes remain ideal for public endpoints or webhooks. Performance is virtually identical under the hood.',
    youtube_reply_id: 'yt-reply-999',
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 550).toISOString(),
  },
  {
    id: 'hist-2',
    comment_id: 'comm-5',
    action: 'rejected',
    action_by: 'Auto Spam Filter',
    reply_text: null,
    youtube_reply_id: null,
    error_message: 'Flagged as WhatsApp / Crypto Scam Spam',
    created_at: new Date(Date.now() - 1000 * 60 * 415).toISOString(),
  },
];

export const INITIAL_ANALYTICS: AnalyticsStats = {
  total_comments: 48,
  pending_count: 4,
  approved_count: 1,
  posted_count: 1,
  rejected_count: 1,
  response_rate: 83.3,
  tone_distribution: {
    positive: 18,
    question: 15,
    criticism: 4,
    funny: 8,
    neutral: 3,
  },
  top_videos: [
    {
      video_id: 'vid-1',
      title: 'Building a Full-Stack AI SaaS with Next.js 15 & Supabase (2026 Guide)',
      comment_count: 42,
      pending_count: 2,
    },
    {
      video_id: 'vid-2',
      title: 'How I Built an Automated YouTube Studio with AI Code Assistants',
      comment_count: 89,
      pending_count: 2,
    },
    {
      video_id: 'vid-3',
      title: 'Top 10 Next.js 15 Features You MUST Use Right Now!',
      comment_count: 124,
      pending_count: 0,
    },
  ],
};
